### PR TITLE
Provide locale_selector upon babel.init_app

### LINKED ISSUE #17: Babel.localeselector missing in flask-babel 3.0.0
> - Babel.locale_selector and Babel.timezone_selector no longer exist. They must be provided
>   either when the Babel() object is created or when init_app() is called. This is to support
>   having a single Babel object for multiple Flask apps (#107) as well as to simplify settings
>   and multi-threaded state.

_https://github.com/python-babel/flask-babel/blob/master/CHANGELOG Section 3.0.0_

One option would be to temporarily pin flask-babel to `2.0.0` as well.

@moridius started working on a proper fix, which gets rid of the decorator.

### PR DESCRIPTION
**Pull request by AiyionPrime**
resolves #17

### CODE REVIEW

**Comment by AiyionPrime** [comment]
@moridius I gave you write access on my fork, feel free to use it for PRs.
Reading the above doc, I think it should be possible to get rid of the `init_app`-line and put the locale selector in line 15 instead.

**Comment by AiyionPrime** [comment]
`babel = Babel(app, locale_selector=get_locale)` if necessary, put get_locale above that line.

Similar to _Example selector functions_ in https://github.com/python-babel/flask-babel/blob/master/docs/index.rst#configuration

**Review by AiyionPrime — COMMENTED** [review]
LGTM

**Comment by AiyionPrime** [comment]
Should be squashed upon merging

**Comment by AiyionPrime** [comment]
Should be squashed upon merging

**Comment by lemoer** [comment]
Thank you. Applied in 7b2d0834153839f611c122de27337f1f07ba0030.

**Pull request closed without merging**
